users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${public_key}

package_update: true
package_upgrade: false

packages:
  - nginx
  - vim
  - curl
  - htop
  - git
  - net-tools

runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - systemctl status nginx || true
  - curl localhost || true

final_message: "VM is up after $UPTIME seconds"